### ISSUE TITLE
pole placement

### ISSUE THREAD

**Issue by weihli** [LozioAlce/L1_AC#1]
@LozioAlce  Hi LozioAlce, You get the feedback gain K by pole placement.  The pole equal to the A matrice's eigenvalues plus matrice [-2.5  -2.5  -2.5  -2.5]', I have doubt in matrice [-2.5 -2.5 -2.5 -2.5],  and how to choose the matrice?

**Comment by LozioAlce** [comment]
Hi,
Well I just tried to put them somewhere where it was stable, without oscillations, real eigenvalues, and about their value, I mainly performed trial and error.
Not too big, otherwise the actuator cannot keep up with the desired dynamic, not too slow either.
In fact if you placed them too big, meaning too fast, the overall behavior tends to be less robust with respect to parameters uncertainty.
At the end to keep things simple a just set then in the same place.
Let me know if changing them, slightly from one another mess things up or not.

**Comment by weihli** [comment]
Thanks for reply.  Through trial and error, You get the desired pole. Have any try to use LQR which can also get feedback gain K.

**Comment by weihli** [comment]
Thanks for reply. Through trial and error, You get the desired pole. Have any try to use LQR which can find optimal gains.

**Comment by LozioAlce** [comment]
We are always talking about state feedback,   therefore pole placement  poles can in principle correspond to LQR resulting poles.
Usually for aircraft, you are more concerned with flying qualities, that directly translate into poles position rather than LQR. Therefore I prefer the pole placement rather than LQR, because it is simpler specify the desired dynamics. 
Try experimenting with LQR is also fine.
Have you tried changing the pole yet?

**Comment by weihli** [comment]
Not yet, I just wanted to use it for the quadcopter, So I replace with quadcopter's nonlinear model.
